export const socialOpsCoreMigration = "0001_socialops_core.sql";

export const sourceOfTruthTables = [
  "users",
  "workspaces",
  "workspace_members",
  "personal_profiles",
  "career_profiles",
  "brand_profiles",
  "agency_clients",
  "projects",
  "campaigns",
  "capture_notes",
  "content_drafts",
  "approval_items",
  "social_identities",
  "social_accounts",
  "content_calendar_items",
  "leads",
  "outreach_messages",
  "content_metrics",
  "media_assets",
  "ugc_briefs",
  "visual_assets",
  "video_templates",
  "video_scripts",
  "video_jobs",
  "video_scenes",
  "video_assets",
  "voiceover_assets",
  "caption_tracks",
  "caption_segments",
  "product_demo_projects",
  "product_demo_scenes",
  "broll_plans",
  "video_post_bridges",
  "decks",
  "applications",
  "application_answers",
  "research_briefs",
  "billing_customers",
  "entitlements",
  "usage_events",
  "audit_logs",
] as const;

export type SourceOfTruthTable = (typeof sourceOfTruthTables)[number];
